ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: $PORT
  jwt:
    secret: "elvoappsecret"
    issuer: "http://localhost:8080"
    audience: "http://localhost:8080"
    realm: "Access protected routes"
    expiry: "900000"
  postgres:
    url: "jdbc:postgresql://hopper.proxy.rlwy.net:20026/railway"
    user: "postgres"
    password: "vvJMCBTTqsDHZfiKLkDgKZvvlFLCvtFs"

