ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: ${PORT}
  jwt:
    secret:  ${JWT_SECRET:"elvoappsecret"}
    issuer: "http://localhost:8080"
    audience: "http://localhost:8080"
    realm: "Access protected routes"
    expiry: "900000"
  postgres:
    url: ${POSTGRES_URL:"postgresql://postgres:vvJMCBTTqsDHZfiKLkDgKZvvlFLCvtFs@hopper.proxy.rlwy.net:20026/railway"}
    user: ${POSTGRES_USER:"postgres"}
    password: ${POSTGRES_PASSWORD:"vvJMCBTTqsDHZfiKLkDgKZvvlFLCvtFs"}
